export enum ENV {
  ENV = 'ENV',
  TYPE = 'TYPE',
  HOST = 'HOST',
  PORT = 'PORT',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  HASH_ROUNDS = 'HASH_ROUNDS',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
}
